minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
strictPeerDependencies: true

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
  esbuild: true
  unrs-resolver: true

overrides:
  'brace-expansion@>=1.0.0 <2.0.0': 1.1.21
  'brace-expansion@>=2.0.0 <3.0.0': 2.1.7
  'defu@<6.1.5': 6.1.7
  'deepmerge-ts@<8.0.0': 8.0.2
  'source-map-js@<1.2.2': 1.2.2
