// 'use client'
import type { Metadata } from "next";

import { BottomMenu, Toaster, TopMenu, WhatsappButton } from "@/components";

export const metadata: Metadata = {
  title: "Mini market",
  // description: "Generated by appncy",
};
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopMenu />

        <main className="py-8 flex justify-center">{children}</main>
        <Toaster />
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} almond_developments
        </footer>
        <WhatsappButton/>

        <BottomMenu/>
        
      </body>
    </html>
  );
}
