
import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";
import { TopMenu } from "@/components";

export const metadata: Metadata = {
  title: "ecommerce-sheets",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="">
          <TopMenu/>
        
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} ecommerce-sheets
        </footer>
      </body>
    </html>
  );
}
