// 'use client'
import type { Metadata } from "next";

import "./globals.css";
import { Toaster, TopMenu } from "@/components";

export const metadata: Metadata = {
  title: "ecommerce-sheets",
  description: "Generated by appncy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopMenu />

        <main className="py-8 flex justify-center">{children}</main>
        <Toaster/>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} almond_developments
        </footer>
      </body>
    </html>
  );
}
